spring:
  datasource:
    url: {DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false

app:
  csrf-enabled: false

jwt:
  expiration-minutes: 30
  cookie-secure: false

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

management:
  endpoints:
    web:
      exposure:
        include: health, metrics
  endpoint:
    health:
      show-details: never

server:
  error:
    include-message: never
    include-stacktrace: never